---
global:
  data:
    domain: global.local
    asn: 1

eu:
  data:
    asn: 65100
    dns_servers:
      - 172.16.1.1
      - 172.16.1.2
    ntp_peers:
      - 10.10.1.1
      - 10.10.2.2
    ntp_servers:
      - 172.16.1.100
      - 172.16.1.10

juniper:
  data:
    local_users:
      - salt:
          class: super-user
          password: $6$upbXDQBFn1SNerkk$r7EPwW1rCpoN/qiAnLugKRakQBwqtDIamY4ODLVJ/1GmYnq04gXNmVXE7IKQUOeQlDfTTUoLgXAy8wgRv1emk0
          uid: 2000
      - inetzero:
          class: supervisor
          password: $6$VOKlkeGfgPovAiaq$Os/RyhfuOFT8unGpqqGJL7.NbBh34tH6pvkeA7V2CcX8a0WCdIzgyEUU8rXs2P9KHB.uztJpWfwLMuITY1F7P0
          uid: 2001
    classes:
      - supervisor



bma:
  groups:
    - eu
    - global

cmh:
  data:
    asn: 65000

