---
r1: 
  hostname: 10.1.1.1
  platform: junos
  groups:
    - bma
    - juniper
  data: 
    site: dub
    type: network_device
    role: router
    loopbackv4: 1.1.1.1/32
    interfaces:
      - ge-0/0/1:
          units:
            "0":
              ipv4addr:
                - 10.10.1.1/24
                - 20.10.1.1/24
              ipv6addr:
                - 2001:db8:0:5::1/64
                - 2001:db8:0:6::1/64
r2: 
  hostname: 10.1.1.2
  platform: junos
  groups:
    - bma
    - juniper
  data: 
    site: dub
    type: network_device
    role: router
    loopbackv4: 2.2.2.2/32
    interfaces:
      - ge-0/0/1:
          units:
            "0":
              ipv4addr:
                - 10.10.1.2/24
                - 20.10.1.2/24
              ipv6addr:
                - 2001:db8:0:5::2/64
                - 2001:db8:0:6::2/64
      - ge-0/0/3:
          units:
            "0":
              ipv4addr:
                - 10.20.1.2/24
              ipv6addr:
                - 2001:db8:0:5::2/64
r3: 
  hostname: 10.1.1.3
  platform: ios
  groups:
    - bma
  data: 
    site: dub
    type: network_device
    role: router
    loopbackv4: 3.3.3.3/32
    interfaces:
      - g0/1:
          description: This is a link
          ipv4addr: 10.20.1.3/24
          ipv6addr: 2001:db8:0:5::3/64
      - g0/3.123:
          description: This is a link
          ipv4addr: 33.33.33.33/24
          ipv6addr: 2001:db8:33:33::33/64
      - g0/2:
          description: This is a link
          ipv4addr: 10.100.1.3/24
          ipv6addr: 2001:db8:0:5::3/64
r4: 
  hostname: 10.1.1.14
  platform: iosxr
  port: 22
  timeout: 120
  groups: [bma]
  data: 
    site: dub
    type: network_device
    role: router
    loopbackv4: 4.4.4.4/32
    interfaces:
      - GigabitEthernet0/0/0/0:
          description: This is a link
          ipv4addr: 10.30.1.6/24
          ipv6addr: 2001:db8:0:5::4/64
      - GigabitEthernet0/0/0/1.999:
          description: This is a link
          ipv4addr: 30.10.1.4/24
          ipv6addr: 2001:db8:0:5::4/64
